name: Bug Report
description: Report a bug to help us improve.
title: "[BUG] : "
labels: [bug]
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report

        Please fill out the information below.

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: Which operating system are you using?
      options:
        - Windows
        - macOS
        - Linux
        - Other
    validations:
      required: true

  - type: dropdown
    id: mac-architecture
    attributes:
      label: Mac Architecture
      description: If you are using macOS, please specify the architecture.
      options:
        - Intel
        - Apple Silicon (M1/M2)
        - Other
    validations:
      required: true
    if:
      contains:
        operating-system:
          - macOS

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: Provide the version of your operating system.
      placeholder: e.g., Windows 10 Pro, macOS Big Sur 11.2.3
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide a step-by-step description of how to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
      placeholder: The application should...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: Describe what actually happened.
      placeholder: Instead of the expected behavior, this happened...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Logs, screenshots, etc.
    validations:
      required: false
